[package]
name = "rindexer_rust_playground"
version = "0.1.0"
edition = "2024"

[dependencies]
# internal dependencies
rindexer = { path = "../../core" }

# external dependencies
tokio = { version = "1", features = ["full"] }
alloy = { version = "1.0.9", features = ["full"] }